/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gtdev_oc_server_JNInterface */

#ifndef _Included_org_gtdev_oc_server_JNInterface
#define _Included_org_gtdev_oc_server_JNInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gtdev_oc_server_JNInterface
 * Method:    println
 * Signature: (ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_gtdev_oc_server_JNInterface_println
  (JNIEnv *, jclass, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
